name: LDAWTS
channels:
- defaults
- conda-forge
- bioconda
dependencies:
- python=3.10.8
- nextflow=23.10.0
- numpy=1.23.5
- pandas=1.5.2
- pip=22.2.2
- sqlite=3.40.0
- tqdm=4.64.1
- tree=2.1.1
- pyarrow
#- img2dataset=1.42.0

